##### FeatureInitializer Config

# default: "", prefix for redis key
redisKeyPrefix:

# default: 0, item slot type on redis cluster. 0 means slot number use the default value 16384, 1 means all keys save to same slot, 2 means use the last character of id as hash tag.
redisClusterItemSlotType: 2

# default: null, one of initialUserDataPath or initialItemDataPath must be
# provided. Only support parquet file
initialUserDataPath: /home/yina/Documents/xuetang/xuetang/part/wnd_user.parquet
initialItemDataPath: /home/yina/Documents/xuetang/xuetang/part/wnd_item.parquet

# default: null, if loadInitialData=true and initialUserDataPath != null, userIDColumn and
# userFeatureColumns must be provided
userIDColumn: user_id
userFeatureColumns: area_code, terminal_type, user_id

# default: null, if loadInitialData=true and initialItemDataPath != null, userIDColumn and
# userFeatureColumns must be provided
itemIDColumn: classroom_id
itemFeatureColumns: maker_name, classify_cn, coursecode_parent_name, classroom_id, course_name, avg_chapter_title, short_intro, avg_video_duration

### Redis Configuration
# default: localhost:6379
# redisUrl: 10.239.158.177:12000,10.239.158.177:12001,10.239.158.177:12002

# default: standalone, redis server type, can be "standalone", "sentinel", or "cluster"
# redisType:

# default: null, must be provided if redisType=sentinel
# redisSentinelMasterName:

# default: localhost:26379
# redisSentinelMasterURL:
