##### RecallInitializer Config

# default: 128, the dimensionality of the embedding vectors
indexDim: 50

# default: null, path to saved index path, must be provided
indexPath: mnt/item.idx

itemIDColumn: tweet_id
itemEmbeddingColumn: prediction

# default: null, Only support parquet file
initialDataPath: mnt/vec_feature_item_prediction.parquet

part: 27
