##### RecallInitializer Config

# default: 128, the dimensionality of the embedding vectors
indexDim:

# default: null, path to saved index path, must be provided
indexPath: ./item_128.idx

itemIDColumn: classroom_id
itemEmbeddingColumn: prediction

# default: null, Only support parquet file
initialDataPath: /home/yina/Documents/xuetang/xuetang/part/item_ebd.parquet

# part: 27
